#######################################
#                                     #
#  Local CVM configuration variables  #
#                                     #
#######################################

# This array includes those Nginx hosts already defined in config.yml because YAML doesn't support extending arrays, just overwriting them.
nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"

  - server_name: "www.demo.dev"
    root: "{{ drupal_composer_site_install_dir }}/demo/web"
    is_php: true

# This array includes those DBs already defined in config.yml because YAML doesn't support extending arrays, just overwriting them.
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

  - name: "{{ drupal_db_name }}_demo"
    encoding: utf8
    collation: utf8_general_ci
