nginx_hosts:
  - server_name: "www.planf.dev"
    root: "{{ drupal_composer_site_install_dir }}/planf/web"
    is_php: true

mysql_databases:
  - name: "{{ drupal_db_name }}_planf"
    encoding: utf8
    collation: utf8_general_ci
